compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: ./deepspeed/ds_2_config_bf16.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
use_cpu: false
