compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: ./deepspeed/ds_3_config_bf16.json
 zero2_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 4 # Adjusted to 4 processes for DS-3 for better performance and resource utilization (if the n of gpus is 4)
use_cpu: false
# This configuration is tailored for DeepSpeed ZeRO-3 with BF16 support.

